@startuml
left to right direction
actor "Usuário comum" as user
actor "Administrador" as admin
actor "Sistema externo" as system
user --> (Gerenciamento Levantamentos)
(Gerenciamento Levantamentos) ..> (Configurar Estratos)
(Gerenciamento Levantamentos) ..> (Gerar Sorteio)
(Gerenciamento Levantamentos) ..> (Registrar Trabalho LIRAa)
(Gerenciamento Levantamentos) ..> (Visualizar Resumo LIRAa)
(Gerenciamento Levantamentos) ..> (Enviar dados LIRAa)
(Configurar Estratos) ..> (Configurar Bairros)
admin --> (Gerenciar usuários)
admin --> (Gerenciar Dashboards)
system --> (Enviar dados LIRAa)
@enduml
